# Pull base image.
FROM jlesage/baseimage-gui:ubuntu-20.04

# Install gimp.
RUN apt-get update && apt-get install -y gimp

# Copy the start script.
COPY startapp.sh /startapp.sh

# Set the name of the application.
ENV APP_NAME="GIMP"
